# Generated by Django 4.1 on 2023-08-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_password_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
